version: '3.8'
services:
  # mysql:
  #   image: mysql:5.7.36
  #   cap_add:
  #     - SYS_NICE
  #   restart: always
  #   ports:
  #     - "33061:3306"
  #   environment:
  #     MYSQL_DATABASE: payroll
  #     MYSQL_USER: rootuser
  #     MYSQL_PASSWORD: secretpw
  #     MYSQL_ROOT_PASSWORD: secretpw
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9015:9015"
    entrypoint: sh /app/docker/startup.local.sh
volumes:
  mysql:
    driver: local